### ISSUE TITLE
Тут либо ошибка, либо объясните как это работает....

### ISSUE THREAD

**Issue by Bugnutiy** [GyverLibs/Hamming#3]
Файл Hamming.h
Срока 84
        if (size & chunkSize != 0) return 0;			// не кратно размеру чанка
Кратность вроде проверяется при помощи %?
Может так оно должно быть?
        if (size % chunkSize != 0) return 0;			// не кратно размеру чанка

**Comment by GyverLibs** [comment]
кратность числу, которое является двойкой в степени минус один, можно проверить через битовую маску, такая операция выполняется в десятки раз быстрее. Но в данном случае действительно ошибка, т.к. потерян этот самый минус один. 
```
if ((size & (chunkSize-1)) != 0) return 0;
```
Спасибо огромное! Ошибка была критическая, я давно уже её искал

**Comment by Bugnutiy** [comment]
Ничего не понял, ибо с битовыми операциями только начал знакомиться, но рад был помочь :D

**Comment by GyverLibs** [comment]
https://alexgyver.ru/lessons/bitmath/
Если число кратно например числу 4, то в двоичной системе оно всегда оканчивается на `00`. А если взять битовую маску И на число 3 (`11` в двоичной), биты взаимообнулятся и получится 0. То же самое будет с любым другим числом из степени двойки

**Comment by Bugnutiy** [comment]
Это понятно, а чему в этот момент должен равняться size и chunksize? И для чего мы chunksize уменьшаем на 1?

**Comment by GyverLibs** [comment]
size должен быть кратен chunksize. Уменьшаем на 1 потому что см урок 
Остаток от деления на `2^n` – битовая маска на n младших битов. Операции остатка от деления `val % (2^n)` можно вычислить через битовую маску: `val & (2^n - 1)`. Например, `val % 8` можно записать как `val & 7`, а `val % 32` можно записать как `val & 31`.

chunksize равен 4, 8, 16, 32 в зависимости от порядка алгоритма

**Comment by Bugnutiy** [comment]
Вот теперь меня прошибло) Спасибо! Ваши либы спасут мир)
