### ISSUE TITLE
PlatformIO публикация

### ISSUE THREAD

**Issue by Bugnutiy** [GyverLibs/Hamming#4]
Обновите пожалуйста библиотеки в PlatformIO, а то там старая версия с багом)

**Comment by GyverLibs** [comment]
Платформио должно само тянуть библиотеку из регистра ардуино. В менеджере ардуино какая версия сейчас?

**Comment by Bugnutiy** [comment]
Как ни странно, в ардуинском всё ок 1.3.1, а в platformio 1.1

**Comment by GyverLibs** [comment]
перезалью попробую

**Comment by Bugnutiy** [comment]
Хмм... Там либо у платформио что-то не так, либо у меня... Я вообще не вижу там свежих либов.

**Comment by GyverLibs** [comment]
не, все обновки льются
![image](https://github.com/GyverLibs/Hamming/assets/84599917/e3d9edba-ba6a-4b03-a950-bde798a6dac9)

**Comment by Bugnutiy** [comment]
Вот на этих библиотеках обновы вижу.... Но там не только от Вас либы застряли с обновами...

**Comment by GyverLibs** [comment]
У ардуино регистра уже пару месяцев как сбой, если зайти на главную и посмотреть свежие либы
https://www.arduinolibraries.info/

**Comment by Bugnutiy** [comment]
Короче, в платформио без изменений)
